/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author firdahilya
 */
public class kuis2 extends javax.swing.JFrame {

    /**
     * Creates new form kuis2
     */
    public kuis2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        proses = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        brg1 = new javax.swing.JTextField();
        brg2 = new javax.swing.JTextField();
        brg3 = new javax.swing.JTextField();
        brg4 = new javax.swing.JTextField();
        diskon = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        hasil = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lithos Pro Regular", 0, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kasir ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 70, 240, 70);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Harga Barang 1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 210, 110, 20);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Harga Barang 2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 260, 110, 20);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Harga Barang 3");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 310, 110, 20);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Harga Barang 4");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 360, 110, 20);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Diskon");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 410, 48, 20);

        proses.setText("Proses");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });
        getContentPane().add(proses);
        proses.setBounds(80, 470, 79, 29);

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus);
        hapus.setBounds(210, 470, 77, 29);

        keluar.setText("Exit");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar);
        keluar.setBounds(350, 470, 59, 29);
        getContentPane().add(brg1);
        brg1.setBounds(240, 210, 181, 26);
        getContentPane().add(brg2);
        brg2.setBounds(240, 260, 181, 26);
        getContentPane().add(brg3);
        brg3.setBounds(240, 310, 181, 26);
        getContentPane().add(brg4);
        brg4.setBounds(240, 360, 181, 26);

        diskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diskonActionPerformed(evt);
            }
        });
        getContentPane().add(diskon);
        diskon.setBounds(240, 410, 181, 30);

        hasil.setColumns(20);
        hasil.setRows(5);
        jScrollPane1.setViewportView(hasil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(110, 520, 282, 140);

        jLabel8.setIcon(new javax.swing.ImageIcon("E:\\ipiners\\ok.png")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, -10, 530, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diskonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diskonActionPerformed

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
        int HB1 = Integer.parseInt(brg1.getText());
        int HB2 = Integer.parseInt(brg2.getText());
        int HB3 = Integer.parseInt(brg3.getText());
        int HB4 = Integer.parseInt(brg4.getText());
        int Diskon = Integer.parseInt(diskon.getText());
        String ket;
      
        
        switch (Diskon) {
            case 50:
                {
                    int total =(HB1+HB2+HB3+HB4);
                    int hasill =(HB1+HB2+HB3+HB4)/2;
                    ket = "Diskon= "+Diskon+"\n"+"Total harga= "+total+"\n"+"Total Bayar = "+hasill;
                    break;
                }
            case 100:
                {
                    int total =(HB1+HB2+HB3+HB4);
                    int hasill =total*0;
                    ket= "Diskon= "+Diskon+"\n"+"Total harga= "+total+"\n"+"Total Bayar = "+hasill;
                    break;
                }
            case 75:
                {
                    int total =(HB1+HB2+HB3+HB4);
                    int hasill =total * Diskon /100;
                    ket = "Diskon= "+Diskon+"\n"+"Total harga= "+total+"\n"+"Total Bayar = "+hasill;
                    break;
                }
            case 0:
                {
                    int total =(HB1+HB2+HB3+HB4);
                    int hasill =total;
                    ket= "Diskon= "+Diskon+"\n"+"Total harga= "+total+"\n"+"Total Bayar = "+hasill;
                    break;
                }
            default:
                ket =" ";
                break;
        }
        hasil.setText("Harga barang1 : " + HB1 + "\n"  +"Harga barang2 : "+ HB2 +  "\n"  +
                " Harga Barang 3 : "  + HB3 +  "\n"  +"Harga Barang 4:   "+ HB4 +"\n"+"        "
                + "Diskon Anda :   "  +  Diskon +   "\n"    + ket);
       
               
        
               
// TODO add your handling code here:
    }//GEN-LAST:event_prosesActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_hapusActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
      dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new kuis2().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brg1;
    private javax.swing.JTextField brg2;
    private javax.swing.JTextField brg3;
    private javax.swing.JTextField brg4;
    private javax.swing.JTextField diskon;
    private javax.swing.JButton hapus;
    private javax.swing.JTextArea hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluar;
    private javax.swing.JButton proses;
    // End of variables declaration//GEN-END:variables
}
