/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author firdahilya
 */
public class kuis1 extends javax.swing.JFrame {

    /**
     * Creates new form kuis1
     */
    public kuis1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TA = new javax.swing.JButton();
        nama = new javax.swing.JTextField();
        absen = new javax.swing.JTextField();
        matpel = new javax.swing.JTextField();
        nilai = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        hasil = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tekton Pro", 1, 35)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 255));
        jLabel1.setText("Penilaian Siswa");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 30, 260, 60);

        jLabel2.setForeground(new java.awt.Color(255, 51, 255));
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(49, 109, 41, 20);

        jLabel3.setForeground(new java.awt.Color(255, 0, 255));
        jLabel3.setText("Absen");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(49, 182, 44, 20);

        jLabel4.setForeground(new java.awt.Color(255, 51, 255));
        jLabel4.setText("Matpel");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(49, 251, 46, 20);

        jLabel5.setForeground(new java.awt.Color(255, 51, 255));
        jLabel5.setText("Nilai");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(49, 329, 31, 20);

        TA.setBackground(new java.awt.Color(102, 0, 102));
        TA.setForeground(new java.awt.Color(255, 51, 255));
        TA.setText("Proses");
        TA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TAActionPerformed(evt);
            }
        });
        getContentPane().add(TA);
        TA.setBounds(180, 380, 79, 29);
        getContentPane().add(nama);
        nama.setBounds(145, 109, 266, 26);
        getContentPane().add(absen);
        absen.setBounds(145, 179, 266, 26);
        getContentPane().add(matpel);
        matpel.setBounds(145, 248, 266, 26);
        getContentPane().add(nilai);
        nilai.setBounds(145, 326, 266, 26);

        hasil.setColumns(20);
        hasil.setRows(5);
        jScrollPane1.setViewportView(hasil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(49, 442, 360, 139);

        jLabel6.setIcon(new javax.swing.ImageIcon("E:\\ipiners\\uuuu.png")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 500, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TAActionPerformed
      String Nama = nama.getText();
         String Absen = absen.getText();
         String Matpel =matpel.getText();
         int Nilai = Integer.parseInt(nilai.getText());
         String Keterangan="";
         if(Nilai == 0){
             Keterangan = "Tidak Lulus";
         }
         else if(Nilai <=75){
             Keterangan = "Lulus";
         }
         else if (Nilai <=90){
             Keterangan = "Lumayan ";
         }
         else if (Nilai == 100){
             Keterangan = "Perfect";
         }
         else if ( Nilai >=100){
             Keterangan = "Subhanaallah";
         }
         else {
             Keterangan ="";
         }
         hasil.setText("Nama Siswa : "+Nama+"\n"+"Absen : "+Absen+"\n"+"Mapel : "
                +Matpel+"\n"+"Nilai : "+Nilai+"\n Keterangan :"+Keterangan);
         
// TODO add your handling code here:
    }//GEN-LAST:event_TAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kuis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kuis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kuis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kuis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kuis1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TA;
    private javax.swing.JTextField absen;
    private javax.swing.JTextArea hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField matpel;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nilai;
    // End of variables declaration//GEN-END:variables
}
