/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author firdahilya
 */
public class Latihan3 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan3
     */
    public Latihan3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bil1 = new javax.swing.JTextField();
        bil2 = new javax.swing.JTextField();
        kali = new javax.swing.JButton();
        bagi = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        kurang = new javax.swing.JButton();
        hacil = new javax.swing.JLabel();
        hasil = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel5.setIcon(new javax.swing.ImageIcon("E:\\ipiners\\calculator-1719738_960_720.png")); // NOI18N

        jPanel1.setBackground(new java.awt.Color(240, 101, 49));
        jPanel1.setLayout(null);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(477, 48, 0, 0);

        jLabel6.setIcon(new javax.swing.ImageIcon("E:\\ipiners\\calculator-1719738_960_720.png")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setText("Bilangan1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 130, 69, 20);

        jLabel3.setText("Bilangan2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 170, 69, 30);

        bil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil1ActionPerformed(evt);
            }
        });
        getContentPane().add(bil1);
        bil1.setBounds(178, 124, 214, 26);
        getContentPane().add(bil2);
        bil2.setBounds(180, 170, 214, 26);

        kali.setText("X");
        kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaliActionPerformed(evt);
            }
        });
        getContentPane().add(kali);
        kali.setBounds(70, 270, 50, 48);

        bagi.setText("\\");
            bagi.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bagiActionPerformed(evt);
                }
            });
            getContentPane().add(bagi);
            bagi.setBounds(170, 270, 51, 48);

            tambah.setText("+");
            tambah.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    tambahActionPerformed(evt);
                }
            });
            getContentPane().add(tambah);
            tambah.setBounds(280, 270, 45, 46);

            kurang.setText("-");
            kurang.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    kurangActionPerformed(evt);
                }
            });
            getContentPane().add(kurang);
            kurang.setBounds(370, 270, 47, 48);

            hacil.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 40)); // NOI18N
            hacil.setForeground(new java.awt.Color(255, 255, 255));
            hacil.setText("Hasil");
            getContentPane().add(hacil);
            hacil.setBounds(190, 420, 210, 41);

            hasil.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    hasilActionPerformed(evt);
                }
            });
            getContentPane().add(hasil);
            hasil.setBounds(90, 500, 290, 68);

            jLabel7.setFont(new java.awt.Font("SimSun", 0, 30)); // NOI18N
            jLabel7.setText("Kalkulator ");
            getContentPane().add(jLabel7);
            jLabel7.setBounds(170, 40, 230, 80);

            jLabel1.setIcon(new javax.swing.ImageIcon("E:\\ipiners\\calculator-1719738_960_720.png")); // NOI18N
            getContentPane().add(jLabel1);
            jLabel1.setBounds(-70, 0, 540, 690);

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangActionPerformed
   int bila1 = Integer.parseInt(bil1.getText());   
   int bila2 = Integer.parseInt(bil2.getText()); 
   int hasil2 = bila1-bila2;
   hasil.setText(String.valueOf(hasil2));
                // TODO add your handling code here:
    }//GEN-LAST:event_kurangActionPerformed

    private void bil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bil1ActionPerformed

    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
   // TODO add your handling code here:
    }//GEN-LAST:event_hasilActionPerformed

    private void bagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagiActionPerformed
   int bila1 = Integer.parseInt(bil1.getText());   
   int bila2 = Integer.parseInt(bil2.getText()); 
   int hasil2 = bila1/bila2;
   hasil.setText(String.valueOf(hasil2));
        // TODO add your handling code here:
    }//GEN-LAST:event_bagiActionPerformed

    private void kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliActionPerformed
   int bila1 = Integer.parseInt(bil1.getText());   
   int bila2 = Integer.parseInt(bil2.getText()); 
   int hasil2 = bila1*bila2;
   hasil.setText(String.valueOf(hasil2));
// TODO add your handling code here:
    }//GEN-LAST:event_kaliActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
   int bila1 = Integer.parseInt(bil1.getText());   
   int bila2 = Integer.parseInt(bil2.getText()); 
   int hasil2 = bila1+bila2;
   hasil.setText(String.valueOf(hasil2));  // TODO add your handling code here:
    }//GEN-LAST:event_tambahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bagi;
    private javax.swing.JTextField bil1;
    private javax.swing.JTextField bil2;
    private javax.swing.JLabel hacil;
    private javax.swing.JTextField hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kali;
    private javax.swing.JButton kurang;
    private javax.swing.JButton tambah;
    // End of variables declaration//GEN-END:variables
}
